### ISSUE TITLE
5.1 Path not relative CakeCLR 38.4

### ISSUE THREAD

**Issue by nick5454** [cake-contrib/Cake.Incubator#114]
On Azure Devops when including Cake.CoreCLR with versions earlier than 33, errors are returned. Locally it works

## Expected Behavior
Installing Cake Addins should succeed.

## Current Behavior
I get a Paths not relative error and I have seen other errors

## Possible Solution
Fix the syntax error, Azure devops is a little different

## Steps to Reproduce (for bugs)
Run the script in an Azure Pipeline

## Context
I have a Cake script to build a project in Cake.CoreCLR with the latest version in AzureDevops Pipeline, but I can't

## Your Environment
Pipeline microsoft Hosted

pool:
  vmImage: 'windows-latest' 

 - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: './build/build_cake.ps1'
        arguments: '--Target=Clean

Error Received:
Running build script...
Module directory does not exist.
NuGet Config not specified. Will use NuGet default mechanism for resolving it.
Analyzing build script...
Analyzing D:/a/1/s/build/Cake/build.cake...
Analyzing D:/a/1/s/build/Cake/paths.cake...
Processing build script...
Installing addins...
Missing C:\Users\VssAdministrator\.nuget\packages\cake.incubator\5.1.0\cake.incubator.5.1.0.nupkg
  GET https://api.nuget.org/v3/registration5-gz-semver2/cake.incubator/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/cake.incubator/index.json 825ms
  GET https://api.nuget.org/v3-flatcontainer/cake.incubator/5.1.0/cake.incubator.5.1.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/cake.incubator/5.1.0/cake.incubator.5.1.0.nupkg 5ms
Acquiring lock for the installation of Cake.Incubator 5.1.0
Acquired lock for the installation of Cake.Incubator 5.1.0
Installing Cake.Incubator 5.1.0.
Completed installation of Cake.Incubator 5.1.0
Error: System.InvalidOperationException: Paths must share a common prefix.
   at Cake.Core.IO.RelativePathResolver.Resolve(DirectoryPath from, DirectoryPath to) in C:\projects\cake\src\Cake.Core\IO\RelativePathResolver.cs:line 36
   at Cake.Core.IO.DirectoryPath.GetRelativePath(FilePath to) in C:\projects\cake\src\Cake.Core\IO\DirectoryPath.cs:line 176
   at Cake.NuGet.NuGetContentResolver.<>c__DisplayClass7_0.<GetAddinAssemblies>b__1(IFile x) in C:\projects\cake\src\Cake.NuGet\NuGetContentResolver.cs:line 87
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Cake.NuGet.NuGetContentResolver.GetAddinAssemblies(DirectoryPath path, PackageReference package) in C:\projects\cake\src\Cake.NuGet\NuGetContentResolver.cs:line 85
   at Cake.NuGet.Install.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path) in C:\projects\cake\src\Cake.NuGet\Install\NuGetPackageInstaller.cs:line 211
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 101
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74

Here is the cake script needed ( Cake.CoreCLR 38.4 )

#addin "nuget:https://api.nuget.org/v3/index.json?package=Cake.Incubator&version=5.1.0"

Task("Clean")
	.Does( ()=> 
{
	Debug("CLEANING!!!!");

	CleanDirectories("./**/obj/*.*");
	CleanDirectories($"./**/bin/{configuration}/*.*");
});

Runtarget("Clean");

**Comment by gep13** [comment]
@nick5454 in order to fully replicate this, we would need the bootstrapper file that you are using?  Could you perhaps create a small GitHub repository, with the the bear minimum of the files needed to replicate the issue, then we might be able to help further.

**Comment by nick5454** [comment]
Turns out there were variables set up which was overriding my cake.config file. It's working now.
