### ISSUE TITLE
With the 1.7.0 release, GetOutputAssemblies for a solution throws an exception

### ISSUE THREAD

**Issue by stevebering** [cake-contrib/Cake.Incubator#59]
I am using Cake.Incubator to build .NET 4.5 solutions. During our build process, we copy output assemblies to an artifacts directory. Today our process, which uses GetOutputAssemblies with a solution file path started failing with the exception "Cannot combine a directory path with an absolute file path." When I rolled by to nuget package with version 1.6.0, my build worked as it had before.

**Comment by wwwlicious** [comment]
@stevebering 👍 Thanks for letting me know and sorry for breaking your build! 
I'll see what I've done to introduce this bug and put a new 1.7.1 release in the next day or so...

As the cake team always recommend, it's always a good idea to pin your build dependency versions as despite my efforts to keep things backwards-compatible and bug free, the odd one does creep in.

**Comment by ayoung** [comment]
Getting the same thing here. Rolling back to 1.6.0.

**Comment by ayoung** [comment]
I caught the stacktrace for this

```
Error: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Cannot combine a directory path with an absolute directory path.
   at Cake.Core.IO.DirectoryPath.Combine(DirectoryPath path) in C:\projects\cake\src\Cake.Core\IO\DirectoryPath.cs:line 88
   at Cake.Incubator.ProjectParserExtensions.<>c__DisplayClass10_0.<GetAssemblyFilePaths>b__0(DirectoryPath x) in C:\projects\cake-incubator\src\Cake.Incubator\ProjectParserExtensions.cs:line 213
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ExceptIterator>d__73`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Submission#0.<<Initialize>>b__0_2()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilderExtensions.cs:line 185
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext() in C:\projects\cake\src\Cake.Core\ActionTask.cs:line 100
```

**Comment by wwwlicious** [comment]
@stevebering @ayoung version 1.7.1 should be available shortly on nuget. Thanks for reporting it. 👍

**Comment by stevebering** [comment]
Thank you for your quick response to this. You guys rock!
