### ISSUE TITLE
ArgumentNullException when parsing project file

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Incubator#76]
I am trying to parse the content of [this project file](https://github.com/ejball/XmlDocMarkdown/blob/master/src/XmlDocMarkdown/XmlDocMarkdown.csproj) but I am getting an `ArgumentNullException`.

The exception is:
```
Value cannot be null.
Parameter name: path
```

The stack trace is:
```
   at Cake.Core.IO.Path..ctor(String path)
   at Cake.Incubator.XDocumentExtensions.<>c__DisplayClass9_0.<GetProjectReferences>b__0(XElement x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Cake.Incubator.XDocumentExtensions.GetProjectReferences(XDocument document, DirectoryPath rootPath)
   at Cake.Incubator.ProjectParserExtensions.ParseVS2017ProjectFile(XDocument document, IFile projectFile, String config, String platform)
   at Cake.Incubator.ProjectParserExtensions.ParseProjectFile(IFile projectFile, String configuration, String platform)
   at Cake.AddinDiscoverer.AddinDiscoverer.GetProjectReferencesAsync(AddinMetadata addin, String projectPath) in E:\_build\Cake.AddinDiscoverer\Source\Cake.AddinDiscoverer\AddinDiscoverer.cs:line 1308
   at Cake.AddinDiscoverer.AddinDiscoverer.<FindReferencesAsync>b__31_0(AddinMetadata addin) in E:\_build\Cake.AddinDiscoverer\Source\Cake.AddinDiscoverer\AddinDiscoverer.cs:line 684
```

I am currently investigating what could be causing this exception but I an opening this issue in case somebody can help me figure this out.

**Comment by Jericho** [comment]
By process of elimination, I was able to figure out that the exception is caused by this section of the `.csproj`:
```
<ItemDefinitionGroup>
  <PackageReference>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <ProjectReference>
    <PrivateAssets>all</PrivateAssets>
  </ProjectReference>
</ItemDefinitionGroup>
```

**Comment by Jericho** [comment]
I have opened an [issue with the Cake.XmlDocMarkdown project](https://github.com/ejball/XmlDocMarkdown/issues/29) to fix their csproj file, but it would probably be a good idea to ensure the project parser in Cake.Incubator is capable of handling this content.

**Comment by wwwlicious** [comment]
Seeing as the empty references are meaningless, I'm not going to handle this as the project files could just be updated to remove the empty tags

**Comment by Jericho** [comment]
I was also under the impression these references were meaningless but turns out that’s no the case. If you look at the issue I previously linked, you’ll see a explanation from the Cake.XmlMarkdown author. 

At the very least, I would think that a more descriptive error message would make it easier to identify this situation.

**Comment by wwwlicious** [comment]
Ah, didn't know there was a catch all...another day, another piece of MSBuild trivia!

I'll try and cater for this global fallback in the next release. In the meantime the worksaround appears to be explicit for each reference.
